### ISSUE TITLE
Hi Mike

### ISSUE THREAD

**Issue by max-prosper** [mikew79/port-domain-service#1]
Thank you for taking the time to complete our test and to agree to provide some improvements.
This is entire part of the interview process.

There are no time constraints from my side, so you can provide fixes and/or discussion on your own time, at your own pace.

**Comment by mikew79** [comment]
Hi Max,

Thanks, they all seem straight forward enough... I believe the recruitment consultant is going to speak with Maria, I am unavailable for the next week, but will complete these as soon as I am back. I will close this issue but leave the remainder open.

Thanks
